config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.FAIR:
    repos:
      this_repo:
        commands:
        - fair-eva.py --id https://zenodo.org/record/3603086 --plugin oai-pmh --repository
          https://zenodo.org/oai2d --api-endpoint http://localhost:9090/v1.0/rda/rda_all
          --json
        container: qc.fair_foggy-tangerine-swan
timeout: 5400
